project:
  type: book

book:
  title: "A Solid Start to ggplot2"
  author: "Joyce Robbins"
  date: today
  site-url: https://jtr13.github.io/graphs
  repo-url: https://github.com/jtr13/graphs
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - grammar.qmd
    - layers.qmd
    - geoms.qmd
    - acknowledgments.qmd
    - references.qmd
    - appendix.qmd

bibliography: references.bib

format:
  html:
    theme: [default, style/graphs.scss]
    code-link: true
    highlight-style: style/joyce.theme
    callout-icon: false
    fig-width: 4
    fig-height: 3
    
knitr:
  opts_chunk: 
    fig.align: center
    out.width: 50%
    
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: false

editor: source

