# Grammar of graphics

The grammar of graphics on which ggplot2 is based on...

```{r}
#| echo: false
library(tidyverse)
library(ggthemes)
library(patchwork)
data_color <- "#008fd5"
fs <- 13

df <- data.frame(state.x77) |> 
  rownames_to_column("State") |> 
  mutate(Region = state.region)

# full graph

ggplot(df, aes(Income/1000, Illiteracy/100)) +
  geom_point(color = data_color) +
  facet_wrap(~Region) +
  scale_x_continuous(name = "Per capita income (in thousands of $)") +
  scale_y_continuous(name = "Illiteracy rate", labels = scales::percent) +
  labs(title = "Illiteracy vs. Income by State") +
  theme_fivethirtyeight(11, base_family = "Chalkboard") +
  theme(plot.title = element_text(size = rel(1.2)),
        axis.title = element_text())

```


## Components


```{r}
#| echo: false
#| fig-height: 2.75
#| fig-width: 7
#| out-width: 70%

p1 <- ggplot(df, aes(Income, Illiteracy)) +
  geom_point(color = data_color) + 
  theme_void(fs) + 
  ggtitle("Layer(s)")

p2 <- ggplot(df, aes(Income, Illiteracy/100)) +
  theme_classic(fs) + 
  ggtitle("Scales") +
  scale_y_continuous(name = "Illiteracy", labels = scales::percent)

p3 <- ggplot(df, aes(Income, Illiteracy/100)) +
  scale_x_continuous(name = NULL) +
  scale_y_continuous(name = NULL) +
  ggtitle("Coordinate System") +
  theme_bw(fs) +
  theme(axis.text = element_blank())

p4 <- ggplot(df, aes(Income, Illiteracy/100)) +
  scale_x_continuous(name = NULL) +
  scale_y_continuous(name = NULL) +
  ggtitle("Faceting") +
  theme_bw(fs) +
  theme(axis.text = element_blank()) +
  facet_wrap(~Region)


p5 <- ggplot(df, aes(Income, Illiteracy/100)) +
  ggtitle("Theme") +
  theme_fivethirtyeight(13, base_family = "Chalkboard") +
  theme(plot.title = element_text(size = rel(1.2)))

p1 + plot_spacer() + p2 + plot_spacer() + p3 + 
  plot_layout(widths = c(.35, .05, .35, .05, .35))
```

```{r}
#| echo: false
#| fig-height: 2.75
#| fig-width: 7
#| out-width: 70%
plot_spacer() + p4 + plot_spacer() + p5 + plot_spacer() + 
  plot_layout(widths = c(.1, .37, .05, .37, .1))
```

